### ISSUE TITLE
more detail in NEWS.md?

### ISSUE THREAD

**Issue by sckott** [ropensci/UCSCXenaTools#20]
hi, thanks for including changes in your NEWS file https://github.com/ropensci/UCSCXenaTools/blob/master/NEWS.md

I wonder if you could include some details of what was done in each release? For example, instead of just 

```
* #14 fixed
```

Include some details of what was done so users can quickly get a sense for the changes that were made

```
* fixed wrong url in the vignette (#14)
```

and having the issue number in parens will link to the issue on github

**Comment by ShixiangWang** [comment]
Dear @sckott,

Thanks for your feedback :), I will include more details in the future releases.

Best,
Shixiang

**Comment by sckott** [comment]
thank you!
