### ISSUE TITLE
Explanation of terms

### ISSUE THREAD

**Issue by adomingues** [ropensci/UCSCXenaTools#23]
First of all thank you for developing this package. I am new to clinical analysis and this package and the vignettes / examples were a good start. 

Regarding the survival analysis [vignette](https://ropensci.org/technotes/2019/09/06/ucscxenatools-surv/), I have been trying to find a resource that explains / maps the variable names in the clinical data table and those used by the studies / Xena. For example the term `OS.time` doesn't show up in my searches of both the Xena portal or the Pan-Cancer Atlas. I am assuming time to remission, but it is just a guess. My question is there is a metadata table that explains what OS.time (and other terms) mean? 

cheers,
António

**Comment by ShixiangWang** [comment]
@adomingues Sorry for the late reply. The vignette you read is out of date and I have updated it recently in my blog https://shixiangwang.github.io/home/en/post/ucscxenatools-201908/. 

For the meaning of `OS.time`, you can read it in most of the datasets in UCSC Xena, such as [LUAD](https://xenabrowser.net/datapages/?dataset=survival%2FLUAD_survival.txt&host=https%3A%2F%2Ftcga.xenahubs.net&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443)

> OS: overall survial
> PFI: progression-free interval
> DSS: disease-specific survival
> DFI: disease-free interval

`OS` data is the most important clinical data, `OS.time` indicates the time range from dignosis to patient's death.

**Comment by adomingues** [comment]
No worries @ShixiangWang. I am happy that now I am a bit more of an explanation about the terms. I read some papers and browsed the resource websites extensible but they have a __lot__ of information. 

Cheers.
